/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package udp;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
      // UdpClient client = new UdpClient();
      // client.execute();
      // Television tv = new Television(7050, "Tele :)");
      // tv.run();
      // w1 -> w2 -> w3 -> w4 -> w1
      WindowPingPong w1, w2, w3, w4;
      w1 = new WindowPingPong(4000, "TV 1");
      w2 = new WindowPingPong(4001, "TV 2");
      w3 = new WindowPingPong(4002, "TV 3");
      w4 = new WindowPingPong(4003, "TV 4");
      // delays ensure the server is up and running by the start of the next thread
      new Thread(() -> w1.run("127.0.0.1", 4001, 1000)).start();
      Thread.sleep(1000);
      new Thread(() -> w2.run("127.0.0.1", 4002, 1000)).start();
      Thread.sleep(1000);
      new Thread(() -> w3.run("127.0.0.1", 4003, 1000)).start();
      Thread.sleep(1000);
      new Thread(() -> w4.run("127.0.0.1", 4000, 1000)).start();
      Thread.sleep(1000);
    }
}
